### ISSUE TITLE
User interface design concepts

### ISSUE THREAD

**Issue by matt-dale** [matt-dale/designdb#2]
**Visual designer**
This concept is not new, but was too difficult to implement for the Beta version.  The goal is to be able to have an accurate image or drawing of every piece of equipment from multiple angles for use in rack drawings, speaker layouts, signal flow diagrams, etc. I'd like to be able to drag and drop items from a palette on the left side of the Location's edit canvas and be able to arrange in any way.

**Comment by gmichael225** [comment]
Gotcha. A bit like Visio symbols?

**Comment by matt-dale** [comment]
Closed -- follow this in issue #6
